title: SPCH2008 BLOG
description: spch2008's blog

url: http://spch2008.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
#- title: About
#  url: /about
#- title: Contact
#  url: /contact

social:
   github: spch2008
   twitter: spch2008
   facebook: spch2008
   email: spch2008@foxmail.com

#google_analytics: "UA-58263416-1"
